<?php
if ( ! current_user_can( 'creditrack_view_reports' ) ) { wp_die( 'Access denied.', '', array( 'response' => 403 ) ); }
$report_type = sanitize_key( $_GET['report_type'] ?? 'portfolio' );
$from = sanitize_text_field( $_GET['from'] ?? gmdate( 'Y-m-01' ) );
$to = sanitize_text_field( $_GET['to'] ?? gmdate( 'Y-m-d' ) );
$result = ( new \CrediTrack\Application\Report_Service() )->generate( $report_type, compact( 'from','to' ) );
$chart_fields = array(
	'portfolio' => array( 'status', 'outstanding', 'Outstanding by loan status' ),
	'disbursements' => array( 'borrower', 'principal', 'Principal disbursed by borrower' ),
	'collections' => array( 'borrower', 'amount', 'Collections by receipt' ),
	'arrears' => array( 'borrower', 'unpaid_amount', 'Arrears by borrower' ),
	'maturity' => array( 'borrower', 'outstanding', 'Outstanding maturity exposure' ),
	'officers' => array( 'officer', 'active_portfolio', 'Active portfolio by loan officer' ),
);
?><div class="ct-titlebar"><div><h1>Reports</h1><div class="ct-muted">Ledger-backed figures as of <?php echo esc_html( wp_date( 'Y-m-d H:i' ) ); ?></div></div></div>
<form class="ct-toolbar" method="get"><label for="report_type">Report</label><select id="report_type" name="report_type"><?php foreach ( array( 'portfolio'=>'Portfolio by status','disbursements'=>'Disbursements','collections'=>'Collections','arrears'=>'Arrears aging','maturity'=>'Maturity','officers'=>'Loan officer performance' ) as $key => $label ) { ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $report_type, $key ); ?>><?php echo esc_html( $label ); ?></option><?php } ?></select><label for="from">From</label><input id="from" name="from" type="date" value="<?php echo esc_attr( $from ); ?>"><label for="to">To</label><input id="to" name="to" type="date" value="<?php echo esc_attr( $to ); ?>"><button type="submit">Generate report</button></form>
<?php if ( is_wp_error( $result ) ) { ?><div class="ct-alert error"><?php echo esc_html( $result->get_error_message() ); ?></div><?php } else {
	$chart = $chart_fields[ $report_type ] ?? null; $chart_rows = array_slice( $result['rows'], 0, 12 );
	if ( $chart && $chart_rows ) { $label_field = $chart[0]; $value_field = $chart[1]; $maximum = max( array_map( static fn( array $row ): float => abs( (float) ( $row[ $value_field ] ?? 0 ) ), $chart_rows ) ); $height = 72 + count( $chart_rows ) * 42; ?>
	<section class="ct-card ct-chart-card"><div class="ct-chart-heading"><div><h2><?php echo esc_html( $chart[2] ); ?></h2><p class="ct-muted">Showing up to 12 rows from the generated report.</p></div><span class="ct-chart-legend"><i></i><?php echo esc_html( $currency ); ?> value</span></div><div class="ct-chart-scroll"><svg class="ct-report-chart" viewBox="0 0 940 <?php echo esc_attr( $height ); ?>" role="img" aria-labelledby="chart-title"><title id="chart-title"><?php echo esc_html( $chart[2] ); ?></title><?php foreach ( $chart_rows as $index => $row ) { $value = (float) ( $row[ $value_field ] ?? 0 ); $width = $maximum > 0 ? abs( $value ) / $maximum * 580 : 0; $y = 48 + $index * 42; $label = wp_html_excerpt( (string) ( $row[ $label_field ] ?? 'Unknown' ), 26, '…' ); ?><text x="0" y="<?php echo esc_attr( $y + 17 ); ?>" class="ct-chart-label"><?php echo esc_html( $label ); ?></text><rect x="210" y="<?php echo esc_attr( $y ); ?>" width="580" height="24" rx="6" class="ct-chart-track"/><rect x="210" y="<?php echo esc_attr( $y ); ?>" width="<?php echo esc_attr( $width ); ?>" height="24" rx="6" class="ct-chart-bar<?php echo $value < 0 ? ' negative' : ''; ?>"><title><?php echo esc_html( $label . ': ' . $currency . number_format_i18n( $value, 2 ) ); ?></title></rect><text x="805" y="<?php echo esc_attr( $y + 17 ); ?>" class="ct-chart-value"><?php echo esc_html( $currency . number_format_i18n( $value, 2 ) ); ?></text><?php } ?></svg></div></section>
	<?php } ?><div class="ct-report-actions"><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'creditrack_action' ); ?><input type="hidden" name="action" value="creditrack_export_report"><input type="hidden" name="report_type" value="<?php echo esc_attr( $report_type ); ?>"><input type="hidden" name="from" value="<?php echo esc_attr( $from ); ?>"><input type="hidden" name="to" value="<?php echo esc_attr( $to ); ?>"><button type="submit">Export CSV</button></form></div><div class="ct-table-wrap"><table><thead><tr><?php foreach ( $result['columns'] as $column ) { ?><th><?php echo esc_html( ucwords( str_replace( '_', ' ', $column ) ) ); ?></th><?php } ?></tr></thead><tbody><?php foreach ( $result['rows'] as $row ) { ?><tr><?php foreach ( $result['columns'] as $column ) { ?><td><?php echo esc_html( $row[ $column ] ?? '' ); ?></td><?php } ?></tr><?php } if ( ! $result['rows'] ) { ?><tr><td colspan="<?php echo esc_attr( count( $result['columns'] ) ); ?>">No records match the selected period.</td></tr><?php } ?></tbody></table></div><?php }
