<?php
defined( 'ABSPATH' ) || exit;
add_action( 'after_setup_theme', static function (): void { add_theme_support( 'title-tag' ); } );
add_action( 'wp_enqueue_scripts', static function (): void { wp_enqueue_style( 'creditrack-portal', get_stylesheet_uri(), array(), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-refinements', get_template_directory_uri() . '/assets/refinements.css', array( 'creditrack-portal' ), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-polish', get_template_directory_uri() . '/assets/polish.css', array( 'creditrack-refinements' ), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-viewport', get_template_directory_uri() . '/assets/viewport.css', array( 'creditrack-polish' ), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-header', get_template_directory_uri() . '/assets/header.css', array( 'creditrack-viewport' ), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-dashboard', get_template_directory_uri() . '/assets/dashboard.css', array( 'creditrack-header' ), wp_get_theme()->get( 'Version' ) ); wp_enqueue_style( 'creditrack-components', get_template_directory_uri() . '/assets/components.css', array( 'creditrack-dashboard' ), wp_get_theme()->get( 'Version' ) ); if ( get_query_var( 'creditrack_portal' ) ) { wp_enqueue_script( 'creditrack-portal', get_template_directory_uri() . '/assets/portal.js', array(), wp_get_theme()->get( 'Version' ), true ); } } );
add_action( 'init', static function (): void { add_rewrite_rule( '^creditrack/?([^/]*)/?$', 'index.php?creditrack_portal=1&creditrack_page=$matches[1]', 'top' ); } );
add_filter( 'query_vars', static function ( array $vars ): array { $vars[] = 'creditrack_portal'; $vars[] = 'creditrack_page'; return $vars; } );
add_filter( 'template_include', static function ( string $template ): string { return get_query_var( 'creditrack_portal' ) ? get_template_directory() . '/portal.php' : $template; } );
add_action( 'after_switch_theme', 'flush_rewrite_rules' );
add_action( 'admin_menu', static function (): void {
	add_theme_page( 'CrediTrack Portal', 'CrediTrack Portal', 'manage_options', 'creditrack-portal', static function (): void {
		$theme = wp_get_theme();
		?><div class="wrap"><h1>CrediTrack Portal</h1><p>The management portal theme for CrediTrack Core, produced by Infinity Lines of Code (Pvt) Ltd.</p><table class="widefat striped" style="max-width:760px"><tbody><tr><th scope="row">Theme version</th><td><?php echo esc_html( $theme->get( 'Version' ) ); ?></td></tr><tr><th scope="row">Core status</th><td><?php echo defined( 'CREDITRACK_VERSION' ) ? esc_html( 'Active — ' . CREDITRACK_VERSION ) : 'CrediTrack Core is not active.'; ?></td></tr><tr><th scope="row">Portal URL</th><td><code><?php echo esc_html( home_url( '/creditrack/dashboard/' ) ); ?></code></td></tr></tbody></table><p><a class="button button-primary" href="<?php echo esc_url( home_url( '/creditrack/dashboard/' ) ); ?>">Open Portal</a><?php if ( defined( 'CREDITRACK_VERSION' ) ) { ?> <a class="button" href="<?php echo esc_url( admin_url( 'admin.php?page=creditrack-settings' ) ); ?>">CrediTrack Settings</a><?php } ?></p><p>Branding, currency, lending defaults, notification policy, permissions, document limits, and retention are managed centrally by CrediTrack Core so the plugin and theme always use the same values.</p></div><?php
	} );
} );
