<?php
defined( 'ABSPATH' ) || exit;
if ( ! is_user_logged_in() ) { auth_redirect(); }
if ( ! current_user_can( 'creditrack_access' ) && ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'Access denied.', 'creditrack' ), '', array( 'response' => 403 ) ); }
nocache_headers();
global $wpdb;
$page = sanitize_key( get_query_var( 'creditrack_page' ) ?: 'dashboard' );
$allowed = array( 'dashboard','clients','loans','payments','reports','notifications','users','audit','settings','backups','profile' );
if ( ! in_array( $page, $allowed, true ) ) { $page = 'dashboard'; }
if ( get_option( 'creditrack_maintenance' ) && ! current_user_can( 'creditrack_manage_backups' ) ) { wp_die( esc_html__( 'CrediTrack is temporarily unavailable for maintenance.', 'creditrack' ), '', array( 'response' => 503 ) ); }
if ( 'profile' !== $page && get_user_meta( get_current_user_id(), 'creditrack_force_password_change', true ) ) { wp_safe_redirect( home_url( '/creditrack/profile/?password_change=required' ) ); exit; }
$settings = get_option( 'creditrack_settings', array() ); $currency = $settings['currency_symbol'] ?? '$'; $base = home_url( '/creditrack/' ); $user = wp_get_current_user();
$role_labels = array( 'creditrack_administrator'=>'Administrator','creditrack_loan_officer'=>'Loan Officer','creditrack_viewer'=>'Viewer','administrator'=>'WordPress Administrator' ); $role = $role_labels[ $user->roles[0] ?? '' ] ?? 'Team member';
$initials = strtoupper( substr( $user->first_name ?: $user->display_name, 0, 1 ) . substr( $user->last_name ?: '', 0, 1 ) ); if ( strlen( $initials ) < 2 ) { $initials = strtoupper( substr( $user->display_name, 0, 2 ) ); }
$unread = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$wpdb->prefix}ct_notifications WHERE user_id=%d AND read_at IS NULL AND dismissed_at IS NULL", get_current_user_id() ) );
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head><body><?php wp_body_open(); ?><div class="ct-layout"><aside class="ct-sidebar" id="ct-sidebar"><div class="ct-brand"><span><?php echo esc_html( $settings['company_name'] ?? 'CrediTrack' ); ?></span></div><nav class="ct-nav" aria-label="Primary"><?php
$nav_link = static function ( string $slug, string $label ) use ( $base, $page ): void { printf( '<a href="%s"%s><span class="ct-nav-dot" aria-hidden="true"></span>%s</a>', esc_url( $base . $slug . '/' ), $page === $slug ? ' aria-current="page"' : '', esc_html( $label ) ); };
foreach ( array( 'dashboard'=>'Dashboard','clients'=>'Clients','loans'=>'Loans','payments'=>'Payments','reports'=>'Reports','notifications'=>'Notifications' ) as $slug => $label ) { $nav_link( $slug, $label ); }
$admin_nav = array(); if ( current_user_can( 'creditrack_manage_users' ) ) { $admin_nav['users']='Users'; } if ( current_user_can( 'creditrack_view_audit' ) ) { $admin_nav['audit']='Audit log'; } if ( current_user_can( 'creditrack_manage_settings' ) ) { $admin_nav['settings']='Settings'; } if ( current_user_can( 'creditrack_manage_backups' ) ) { $admin_nav['backups']='Backups'; }
if ( $admin_nav ) { $admin_open = isset( $admin_nav[ $page ] ); ?><details class="ct-nav-group" <?php echo $admin_open ? 'open' : ''; ?>><summary><span class="ct-nav-dot" aria-hidden="true"></span>Administration<span class="ct-nav-chevron" aria-hidden="true">⌄</span></summary><div><?php foreach ( $admin_nav as $slug => $label ) { $nav_link( $slug, $label ); } ?></div></details><?php }
$nav_link( 'profile', 'Profile' );
?></nav><div class="ct-product">A product of<br><strong>Infinity Lines of Code (Pvt) Ltd</strong></div></aside><main class="ct-main"><header class="ct-header"><button class="ct-mobile-menu ct-icon-button" type="button" aria-label="Toggle navigation" aria-controls="ct-sidebar" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><div class="ct-header-spacer"></div><a class="ct-icon-button ct-bell" href="<?php echo esc_url( $base . 'notifications/' ); ?>" aria-label="<?php echo esc_attr( $unread . ' unread notifications' ); ?>"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><?php if ( $unread ) { ?><span><?php echo esc_html( min( 99, $unread ) ); ?></span><?php } ?></a><div class="ct-profile-menu"><button class="ct-profile-trigger" type="button" aria-haspopup="menu" aria-expanded="false"><span class="ct-avatar"><?php echo esc_html( $initials ); ?></span><span class="ct-profile-copy"><strong><?php echo esc_html( $user->display_name ); ?></strong><small><?php echo esc_html( $role ); ?></small></span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="ct-profile-dropdown" role="menu" hidden><div class="ct-dropdown-identity"><strong><?php echo esc_html( $user->display_name ); ?></strong><small><?php echo esc_html( $user->user_email ); ?></small></div><a role="menuitem" href="<?php echo esc_url( $base . 'profile/' ); ?>">Profile &amp; security</a><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'creditrack_action' ); ?><input type="hidden" name="action" value="creditrack_lock_session"><button role="menuitem" type="submit">Lock session</button></form><a class="ct-signout" role="menuitem" href="<?php echo esc_url( wp_logout_url( home_url() ) ); ?>">Sign out</a></div></div></header><div class="ct-content"><?php
if ( isset( $_GET['ct_error'] ) ) { echo '<div class="ct-alert error" role="alert">' . esc_html( sanitize_text_field( wp_unslash( $_GET['ct_error'] ) ) ) . '</div>'; }
if ( isset( $_GET['ct_success'] ) ) { echo '<div class="ct-alert" role="status">Changes saved successfully.</div>'; }
$view = get_template_directory() . '/views/' . $page . '.php'; if ( is_readable( $view ) ) { require $view; }
?></div></main></div><?php wp_footer(); ?></body></html>
