<?php
namespace CrediTrack\Application;

use CrediTrack\Infrastructure\Audit;
use WP_Error;

final class Backup_Service {
	private const TABLES = array( 'clients','client_documents','loans','schedules','payments','payment_allocations','audit_logs','notifications' );

	public function create( string $type = 'manual' ): int|WP_Error {
		if ( ! current_user_can( 'creditrack_manage_backups' ) ) { return new WP_Error( 'forbidden', 'You cannot create backups.' ); }
		if ( ! class_exists( '\ZipArchive' ) ) { return new WP_Error( 'zip', 'PHP ZipArchive is required for application backups.' ); }
		global $wpdb; $directory = self::directory(); if ( is_wp_error( $directory ) ) { return $directory; } $key = gmdate( 'Ymd-His' ) . '-' . bin2hex( random_bytes( 6 ) ); $path = trailingslashit( $directory ) . 'creditrack-' . $key . '.zip'; $now = gmdate( 'Y-m-d H:i:s' );
		$wpdb->insert( $wpdb->prefix . 'ct_jobs', array( 'job_key' => $key, 'type' => $type, 'status' => 'running', 'protected_path' => $path, 'created_by' => get_current_user_id(), 'created_at' => $now, 'updated_at' => $now ) ); $job_id = (int) $wpdb->insert_id;
		$zip = new \ZipArchive(); if ( true !== $zip->open( $path, \ZipArchive::CREATE | \ZipArchive::OVERWRITE ) ) { return new WP_Error( 'backup', 'The backup archive could not be created.' ); }
		$checksums = array(); foreach ( self::TABLES as $suffix ) { $json = wp_json_encode( $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}ct_$suffix", ARRAY_A ), JSON_UNESCAPED_SLASHES ); $name = 'tables/' . $suffix . '.json'; $zip->addFromString( $name, $json ); $checksums[ $name ] = hash( 'sha256', $json ); }
		$settings_json = wp_json_encode( get_option( 'creditrack_settings', array() ), JSON_UNESCAPED_SLASHES ); $zip->addFromString( 'settings.json', $settings_json ); $checksums['settings.json'] = hash( 'sha256', $settings_json );
		$documents = $wpdb->get_results( "SELECT stored_name,protected_path FROM {$wpdb->prefix}ct_client_documents", ARRAY_A ); foreach ( $documents as $document ) { if ( is_readable( $document['protected_path'] ) && self::safe_private_path( $document['protected_path'] ) ) { $name = 'documents/' . basename( $document['stored_name'] ); $zip->addFile( $document['protected_path'], $name ); $checksums[ $name ] = hash_file( 'sha256', $document['protected_path'] ); } }
		$manifest = array( 'product' => 'CrediTrack by Infinity Lines of Code (Pvt) Ltd', 'created_at' => $now, 'schema_version' => get_option( 'creditrack_schema_version' ), 'plugin_version' => CREDITRACK_VERSION, 'site_url_hash' => hash( 'sha256', home_url() ), 'checksums' => $checksums ); $zip->addFromString( 'manifest.json', wp_json_encode( $manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) ); $zip->close();
		$wpdb->update( $wpdb->prefix . 'ct_jobs', array( 'status' => 'completed', 'file_size' => filesize( $path ), 'updated_at' => gmdate( 'Y-m-d H:i:s' ), 'completed_at' => gmdate( 'Y-m-d H:i:s' ) ), array( 'id' => $job_id ) ); Audit::record( 'backup', $job_id, 'create', array(), array( 'job_key' => $key ), 'Application backup created' ); return $job_id;
	}

	public function stream( int $id ): never {
		if ( ! current_user_can( 'creditrack_manage_backups' ) ) { wp_die( 'Access denied.', '', array( 'response' => 403 ) ); } global $wpdb; $job = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}ct_jobs WHERE id=%d AND status='completed'", $id ), ARRAY_A ); if ( ! $job || ! self::safe_private_path( $job['protected_path'] ) || ! is_readable( $job['protected_path'] ) ) { wp_die( 'Backup not found.', '', array( 'response' => 404 ) ); } Audit::record( 'backup', $id, 'download', array(), array(), 'Application backup downloaded' ); nocache_headers(); header( 'X-Content-Type-Options: nosniff' ); header( 'Content-Type: application/zip' ); header( 'Content-Disposition: attachment; filename="' . basename( $job['protected_path'] ) . '"' ); header( 'Content-Length: ' . filesize( $job['protected_path'] ) ); readfile( $job['protected_path'] ); exit;
	}

	public function restore( array $file, string $password, string $confirmation ): true|WP_Error {
		if ( ! current_user_can( 'creditrack_manage_backups' ) ) { return new WP_Error( 'forbidden', 'You cannot restore backups.' ); }
		$user = wp_get_current_user(); if ( ! wp_check_password( $password, $user->user_pass, $user->ID ) ) { return new WP_Error( 'password', 'Your current password is incorrect.' ); } if ( 'RESTORE CREDITRACK' !== $confirmation ) { return new WP_Error( 'confirmation', 'Type RESTORE CREDITRACK exactly to confirm.' ); }
		if ( UPLOAD_ERR_OK !== (int) ( $file['error'] ?? UPLOAD_ERR_NO_FILE ) || ! is_uploaded_file( $file['tmp_name'] ?? '' ) || ! class_exists( '\ZipArchive' ) ) { return new WP_Error( 'upload', 'Select a valid CrediTrack ZIP backup.' ); }
		$pre = $this->create( 'pre-restore' ); if ( is_wp_error( $pre ) ) { return new WP_Error( 'pre_backup', 'Restore stopped because the pre-restore backup failed: ' . $pre->get_error_message() ); }
		$zip = new \ZipArchive(); if ( true !== $zip->open( $file['tmp_name'] ) ) { return new WP_Error( 'archive', 'The backup archive is unreadable.' ); } $manifest_json = $zip->getFromName( 'manifest.json' ); $manifest = json_decode( $manifest_json ?: '', true ); if ( ! is_array( $manifest ) || empty( $manifest['checksums'] ) || version_compare( (string) ( $manifest['schema_version'] ?? '0' ), (string) get_option( 'creditrack_schema_version' ), '>' ) ) { $zip->close(); return new WP_Error( 'manifest', 'Backup manifest is invalid or requires a newer CrediTrack schema.' ); }
		foreach ( $manifest['checksums'] as $name => $expected ) { $contents = $zip->getFromName( $name ); if ( false === $contents || ! hash_equals( $expected, hash( 'sha256', $contents ) ) ) { $zip->close(); return new WP_Error( 'integrity', 'Backup integrity verification failed for ' . sanitize_text_field( $name ) . '.' ); } }
		global $wpdb; update_option( 'creditrack_maintenance', 1 ); $wpdb->query( 'START TRANSACTION' );
		try { foreach ( array_reverse( self::TABLES ) as $suffix ) { $wpdb->query( "DELETE FROM {$wpdb->prefix}ct_$suffix" ); } foreach ( self::TABLES as $suffix ) { $rows = json_decode( $zip->getFromName( 'tables/' . $suffix . '.json' ), true ); if ( ! is_array( $rows ) ) { throw new \RuntimeException( 'Invalid table payload.' ); } foreach ( $rows as $row ) { if ( 'client_documents' === $suffix && isset( $row['stored_name'] ) ) { $row['protected_path'] = trailingslashit( WP_CONTENT_DIR ) . 'creditrack-private/' . basename( $row['stored_name'] ); } if ( false === $wpdb->insert( $wpdb->prefix . 'ct_' . $suffix, $row ) ) { throw new \RuntimeException( 'A table row could not be restored.' ); } } } $settings = json_decode( $zip->getFromName( 'settings.json' ), true ); if ( ! is_array( $settings ) ) { throw new \RuntimeException( 'Invalid settings payload.' ); } update_option( 'creditrack_settings', $settings ); $private = self::directory(); if ( is_wp_error( $private ) ) { throw new \RuntimeException( $private->get_error_message() ); } foreach ( $manifest['checksums'] as $name => $hash ) { if ( str_starts_with( $name, 'documents/' ) ) { file_put_contents( trailingslashit( $private ) . basename( $name ), $zip->getFromName( $name ) ); } } $wpdb->query( 'COMMIT' ); } catch ( \Throwable $error ) { $wpdb->query( 'ROLLBACK' ); delete_option( 'creditrack_maintenance' ); $zip->close(); return new WP_Error( 'restore', 'Restore failed safely: ' . $error->getMessage() ); }
		$zip->close(); delete_option( 'creditrack_maintenance' ); Audit::record( 'backup', $pre, 'restore', array(), array(), 'Application backup restored after integrity validation' ); \WP_Session_Tokens::get_instance( $user->ID )->destroy_others( wp_get_session_token() ); return true;
	}
	private static function directory(): string|WP_Error { $private = trailingslashit( WP_CONTENT_DIR ) . 'creditrack-private'; $base = $private . '/backups'; if ( ! wp_mkdir_p( $base ) ) { return new WP_Error( 'storage', 'Protected backup storage is unavailable.' ); } if ( ! file_exists( $private . '/index.php' ) ) { file_put_contents( $private . '/index.php', "<?php\nhttp_response_code(404);\nexit;\n" ); } if ( ! file_exists( $private . '/.htaccess' ) ) { file_put_contents( $private . '/.htaccess', "Require all denied\nDeny from all\n" ); } return $base; }
	private static function safe_private_path( string $path ): bool { $base = realpath( trailingslashit( WP_CONTENT_DIR ) . 'creditrack-private' ); $real = realpath( $path ); return $base && $real && str_starts_with( wp_normalize_path( $real ), trailingslashit( wp_normalize_path( $base ) ) ); }
}
